#!/bin/bash

####################################################
# Athor: Md. Waliul Islam Rayhan
# Date: 25 Nov 2023
# Version: v1
# This script will report the AWS resource usage
####################################################

# jq = JSON processor

# This is used for Debug
#set -x

# AWS EC2
# AWS S3

Subject: Report AWS usage

# File to store the script output
output_file="/path/to/output.txt"

# Run the AWS commands and store the output in a file
echo -e "List of S3 Bucket" > "$output_file"
aws s3 ls >> "$output_file"
echo -e "\n" >> "$output_file"

echo -e "List of EC2 Instance IDs" >> "$output_file"
aws ec2 describe-instances | jq -r '.Reservations[].Instances[].InstanceId' >> "$output_file"
echo -e "\n" >> "$output_file"


# Send the email using the mail command
sendmail username@gmail.com  < "$output_file"
