#!/bin/bash

####################################################
# Athor: Md. Waliul Islam Rayhan
# Date: 25 Nov 2023
# Version: v1
# This script will report the AWS resource usage
####################################################

# jq = JSON processor

# This is used for Debug
#set -x

# AWS EC2
# AWS S3

echo -e "List of S3 Bucket"
aws s3 ls
echo -e "\n"

echo -e "List of Ec2 Instance"
#aws ec2 describe-instances

aws ec2 describe-instances | jq '.Reservations[].Instances[].InstanceId'
echo -e "\n"
